export function cleanEvent(event: any) {
  return {
    id: event.api_id,
    cover_url: event.cover_url,
    created_at: event.created_at,
    duration_interval: event.duration_interval,
    end_at: event.end_at,
    event_type: event.event_type,
    font_title: event.font_title,
    hide_rsvp: event.hide_rsvp,
    location_type: event.location_type,
    min_ticket_price_cents: event.min_ticket_price_cents,
    name: event.name,
    one_to_one: event.one_to_one,
    phone_number_requirement: event.phone_number_requirement,
    registration_questions: event.registration_questions,
    require_rsvp_approval: event.require_rsvp_approval,
    series_registration_mode: event.series_registration_mode,
    session_count_future: event.session_count_future,
    session_count_total: event.session_count_total,
    session_price_cents: event.session_price_cents,
    show_guest_list: event.show_guest_list,
    start_at: event.start_at,
    theme_meta: event.theme_meta,
    ticket_currency: event.ticket_currency,
    ticket_price_cents: event.ticket_price_cents,
    timezone: event.timezone,
    tint_color: event.tint_color,
    url: event.url,
    visibility: event.visibility,
    waitlist_enabled: event.waitlist_enabled,
    description: event.description,
    is_blocked: event.is_blocked,
    ticket_info: event.ticket_info,
    spots_remaining: event.spots_remaining,
    virtual_info: event.virtual_info,
    geo_longitude: event.geo_longitude,
    geo_latitude: event.geo_latitude,
    geo_address_visibility: event.geo_address_visibility,
    geo_address_info: event.geo_address_info,
    is_capped: event.is_capped,
    session_details: event.session_details,
    is_paid: event.is_paid,
    event_tickets: event.event_tickets,
  };
}

export function cleanUser(user: any) {
  return {
    id: user.api_id,
    email: user.email,
    company: user.company,
    avatar_url: user.avatar_url,
    bio_short: user.bio_short,
    instagram_handle: user.instagram_handle,
    last_online_at: user.last_online_at,
    linkedin_handle: user.linkedin_handle,
    name: user.name,
    tiktok_handle: user.tiktok_handle,
    timezone: user.timezone,
    twitter_handle: user.twitter_handle,
    url: user.url,
    username: user.username,
    website: user.website,
    youtube_handle: user.youtube_handle,
  };
}
